export const OFFCHAIN_SESSION_KEYS_EXECUTE_POPUP_WIDTH = 1
export const OFFCHAIN_SESSION_KEYS_EXECUTE_POPUP_HEIGHT = 1

/* all these sizes are optimistic */
export const EXECUTE_POPUP_WIDTH = 385
export const EXECUTE_POPUP_HEIGHT = 775

export const SIGN_MESSAGE_POPUP_WIDTH = 385
export const SIGN_MESSAGE_POPUP_HEIGHT = 440

export const ENABLE_POPUP_WIDTH = 886
export const ENABLE_POPUP_HEIGHT = 562
